# electron-builder can target win,mac and linux
# just use it for everything

os: osx
osx_image: xcode11.3
language: node_js
node_js: "lts/*"
  
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.m2/repository

install:
  - yarn

script:
  - |
    export ELECTRON_CACHE=$HOME/.cache/electron
    export ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    
    security create-keychain -p $KEYCHAIN_PASSWORD build.keychain;
    security default-keychain -s build.keychain;
    security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain;
    echo $KEYSTORE | base64 --decode - > keystore.p12;
    security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign;
    yarn install
    yarn run build
    yarn run dist-mwl
    
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  # TODO use $TRAVIS_TAG?
  file:
    - dist/observideo-amd64.deb
    - dist/observideo-Setup.exe
    - dist/observideo-mac.zip
  skip_cleanup: true
  on:
    tags: true
