matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      language: node_js
      node_js: "lts/*"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    # Windows currently doesn't support encrypted variables.
    # Once supported uncomment this out & remove build with Docker
    #
    #- os: windows
    #  language: node_js
    #  node_js: "8"

    - os: linux
      services: docker
      language: java
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.m2/repository

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install yarn;
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm install
      npm run release
      npm run dist
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm install
      npm run release
      npm run dist --win
    else
      yarn install
      yarn run release
      yarn run dist --mac
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine