# electron-builder can target win,mac and linux
# just use it for everything

os: osx
osx_image: xcode11.3
language: node_js
node_js: "lts/*"
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.m2/repository

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install yarn;
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm install
      npm run release
      npm run dist
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm install
      npm run release
      npm run dist --win
    else
      yarn install
      yarn run release
      yarn run dist-mwl
    fi
    
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN  
  file:
    - dist/observideo_1.0.0_amd64.deb
    - dist/observideo Setup 1.0.0.exe
    - dist/observideo-1.0.0-mac.zip
  on:
    tags: true
