image: macos

environment:
  - ELECTRON_CACHE: ~/.cache/electron
  - ELETCRON_BUILDER_CACHE: ~/.cache/electron-builder

cache:
  - node_modules
  - ~/.cache/electron
  - ~/.cache/electron-builder
  - ~/.m2/repository

init:
  - git config --global core.autocrlf input

install:
  - npm install

build_script:
  - npm run build
  - npm run dist-mwl

test: off
