image: macos

cache:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.m2/repository

init:
  - git config --global core.autocrlf input

install:
  - npm install

build_script:
  - npm run build
  - npm run dist-mwl

test: off
